name: schedule job

on:
  schedule: 
  - cron: "0 0 * * *"
  # minute, hour, date, month, year
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: print message
      run: echo "schedule workflow execute"
